/*
 * Please do not edit this file too much.
 * It was generated using rpcgen, and then hacked to fix compilation problems.
 */

#include <nfs/nfs.h>
#include "portmap_rpc.h"

bool_t
xdr_mapping (XDR *xdrs, mapping *objp)
{
         if (!xdr_u_int (xdrs, &objp->prog))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->vers))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->prot))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->port))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_pmaplist (XDR *xdrs, pmaplist *objp)
{
         if (!xdr_mapping (xdrs, &objp->map))
                 return FALSE;
         if (!xdr_pointer (xdrs, (void *)&objp->next, sizeof (pmaplist), (xdrproc_t) xdr_pmaplist))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_call_args (XDR *xdrs, call_args *objp)
{
         if (!xdr_u_int (xdrs, &objp->prog))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->vers))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->proc))
                 return FALSE;
         if (!xdr_bytes (xdrs, (char **)&objp->args.args_val, (u_int *) &objp->args.args_len, ~0))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_call_result (XDR *xdrs, call_result *objp)
{
         if (!xdr_u_int (xdrs, &objp->port))
                 return FALSE;
         if (!xdr_bytes (xdrs, (char **)&objp->res.res_val, (u_int *) &objp->res.res_len, ~0))
                 return FALSE;
        return TRUE;
}
