/*
 * Please do not edit this file too much.
 * It was generated using rpcgen, and then hacked to fix compilation problems.
 */

#ifndef _PORTMAP_H_RPCGEN
#define _PORTMAP_H_RPCGEN

// #include "rpc.h"

#ifdef __cplusplus
extern "C" {
#endif

#define PMAP_PORT 111

struct mapping {
    u_int prog;
    u_int vers;
    u_int prot;
    u_int port;
};
typedef struct mapping mapping;
#define IPPROTO_TCP 6
#define IPPROTO_UDP 17

struct pmaplist {
    mapping map;
    struct pmaplist *next;
};
typedef struct pmaplist pmaplist;

struct call_args {
    u_int prog;
    u_int vers;
    u_int proc;
    struct {
        u_int args_len;
        char *args_val;
    } args;
};
typedef struct call_args call_args;

struct call_result {
    u_int port;
    struct {
        u_int res_len;
        char *res_val;
    } res;
};
typedef struct call_result call_result;

#define PMAP_PROG 100000
#define PMAP_VERS 2

#define PMAPPROC_NULL 0
#define PMAPPROC_SET 1
#define PMAPPROC_UNSET 2
#define PMAPPROC_GETPORT 3
#define PMAPPROC_DUMP 4
#define PMAPPROC_CALLIT 5

#if 0
extern  enum clnt_stat pmapproc_null_2(void *, void *, CLIENT *);
extern  enum clnt_stat pmapproc_set_2(mapping *, bool_t *, CLIENT *);
extern  enum clnt_stat pmapproc_unset_2(mapping *, bool_t *, CLIENT *);
extern  enum clnt_stat pmapproc_getport_2(mapping *, u_int *, CLIENT *);
extern  enum clnt_stat pmapproc_dump_2(void *, pmaplist *, CLIENT *);
extern  enum clnt_stat pmapproc_callit_2(call_args *, call_result *, CLIENT *);
#endif

/* the xdr functions */
extern  bool_t xdr_mapping (XDR *, mapping*);
extern  bool_t xdr_pmaplist (XDR *, pmaplist*);
extern  bool_t xdr_call_args (XDR *, call_args*);
extern  bool_t xdr_call_result (XDR *, call_result*);

#ifdef __cplusplus
}
#endif

#endif /* !_PORTMAP_H_RPCGEN */
